// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY7sNb6h1ltdgZwepJOxRgXowERNZtDFM',
    appId: '1:701191082956:web:75b17064a853ea95bdc369',
    messagingSenderId: '701191082956',
    projectId: 'chinaragro-89cdc',
    authDomain: 'chinaragro-89cdc.firebaseapp.com',
    storageBucket: 'chinaragro-89cdc.firebasestorage.app',
    measurementId: 'G-K6H1BTPN0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmpIdFdT3ivxyovxZOKB2GBh1kk3FMRgg',
    appId: '1:701191082956:android:95d66ecbb6b2893ebdc369',
    messagingSenderId: '701191082956',
    projectId: 'chinaragro-89cdc',
    storageBucket: 'chinaragro-89cdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXO1HKHv62JqLNFk5wIKd7dO5v0x8qdDU',
    appId: '1:701191082956:ios:17ed6b3c010c898bbdc369',
    messagingSenderId: '701191082956',
    projectId: 'chinaragro-89cdc',
    storageBucket: 'chinaragro-89cdc.firebasestorage.app',
    iosBundleId: 'com.example.chinarDairy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXO1HKHv62JqLNFk5wIKd7dO5v0x8qdDU',
    appId: '1:701191082956:ios:17ed6b3c010c898bbdc369',
    messagingSenderId: '701191082956',
    projectId: 'chinaragro-89cdc',
    storageBucket: 'chinaragro-89cdc.firebasestorage.app',
    iosBundleId: 'com.example.chinarDairy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY7sNb6h1ltdgZwepJOxRgXowERNZtDFM',
    appId: '1:701191082956:web:a38c3a93df00a54abdc369',
    messagingSenderId: '701191082956',
    projectId: 'chinaragro-89cdc',
    authDomain: 'chinaragro-89cdc.firebaseapp.com',
    storageBucket: 'chinaragro-89cdc.firebasestorage.app',
    measurementId: 'G-8S4Z2CXTHJ',
  );
}
