import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:flutter/foundation.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

// NEW: Import the options file generated by FlutterFire CLI
import 'firebase_options.dart'; 

import 'providers/auth_provider.dart';
import 'providers/cart_provider.dart';
import 'providers/product_provider.dart';
import 'providers/subscription_provider.dart';
import 'providers/wallet_provider.dart';
import 'providers/order_provider.dart';
import 'providers/address_provider.dart';
import 'providers/referal_provider.dart';

import 'screens/splash_screen.dart';
import 'screens/auth/login_screen.dart';
import 'screens/auth/otp_screen.dart';
import 'screens/zone_selection_screen.dart';
import 'screens/main_screen.dart';
import 'screens/product_detail_screen.dart';
import 'screens/subscription_screen.dart';
import 'screens/address_selection_screen.dart';
import 'screens/address_management.dart';
import 'screens/cart_screen.dart';
import 'screens/payment_screen.dart';
import 'screens/profile_screen.dart';
import 'screens/referal_screen.dart';
import 'screens/wallet_screen.dart';
import 'screens/invoices_screen.dart';

import 'utils/theme.dart';

// --- SETUP FOR LOCAL NOTIFICATIONS ---
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

const AndroidNotificationChannel channel = AndroidNotificationChannel(
  'high_importance_channel', 
  'High Importance Notifications', 
  description: 'This channel is used for important notifications.', 
  importance: Importance.max,
);

// --- BACKGROUND MESSAGE HANDLER ---
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // CRITICAL FIX: Ensure background messages use the generated options too
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  debugPrint("Handling a background message: ${message.messageId}");

  RemoteNotification? notification = message.notification;
  AndroidNotification? android = message.notification?.android;

  if (notification != null && android != null) {
    flutterLocalNotificationsPlugin.show(
      notification.hashCode,
      notification.title,
      notification.body,
      NotificationDetails(
        android: AndroidNotificationDetails(
          channel.id,
          channel.name,
          channelDescription: channel.description,
          icon: '@mipmap/ic_launcher', 
        ),
      ),
    );
  }
}

// --- NOTIFICATION PERMISSION & TOKEN HANDLER ---
Future<void> initializeNotificationsAndSaveToken(String customerId) async {
  if (customerId.isEmpty) return;

  FirebaseMessaging messaging = FirebaseMessaging.instance;

  NotificationSettings settings = await messaging.requestPermission(
    alert: true,
    badge: true,
    sound: true,
    provisional: false,
  );

  if (settings.authorizationStatus == AuthorizationStatus.authorized) {
    debugPrint('Notification permission granted.');
    String? fcmToken = await messaging.getToken();
    if (fcmToken != null) {
      debugPrint('FCM Token: $fcmToken');
      try {
        await FirebaseFirestore.instance
            .collection('customers')
            .doc(customerId)
            .set({'fcmToken': fcmToken}, SetOptions(merge: true));
        debugPrint('FCM token saved successfully for customer: $customerId');
      } catch (e) {
        debugPrint('Error saving FCM token: $e');
      }
    }
  } else {
    debugPrint('User declined or has not accepted notification permission');
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // CRITICAL FIX: Initialize with current platform options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(channel);
  
  const AndroidInitializationSettings initializationSettingsAndroid =
      AndroidInitializationSettings('@mipmap/ic_launcher');
  const InitializationSettings initializationSettings =
      InitializationSettings(android: initializationSettingsAndroid);
  await flutterLocalNotificationsPlugin.initialize(initializationSettings);

  FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    debugPrint("Handling a foreground message: ${message.messageId}");
    RemoteNotification? notification = message.notification;
    AndroidNotification? android = message.notification?.android;

    if (notification != null && android != null) {
      flutterLocalNotificationsPlugin.show(
        notification.hashCode,
        notification.title,
        notification.body,
        NotificationDetails(
          android: AndroidNotificationDetails(
            channel.id,
            channel.name,
            channelDescription: channel.description,
            icon: '@mipmap/ic_launcher',
          ),
        ),
      );
    }
  });

  // Activate Firebase App Check.
  if (kDebugMode) {
    await FirebaseAppCheck.instance.activate(
      androidProvider: AndroidProvider.debug,
      appleProvider: AppleProvider.debug,
    );
  } else {
    await FirebaseAppCheck.instance.activate(
      androidProvider: AndroidProvider.playIntegrity,
      appleProvider: AppleProvider.appAttest,
    );
  }
  
  runApp(const ChinaarDairyApp());
}

class ChinaarDairyApp extends StatelessWidget {
  const ChinaarDairyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => CartProvider()),
        ChangeNotifierProvider(create: (_) => ProductProvider()),
        ChangeNotifierProvider(create: (_) => SubscriptionProvider()),
        ChangeNotifierProvider(create: (_) => WalletProvider()),
        ChangeNotifierProvider(create: (_) => OrderProvider()),
        ChangeNotifierProvider(create: (_) => ReferralProvider()),
        ChangeNotifierProvider(create: (_) => AddressProvider()),
      ],
      child: MaterialApp(
        title: 'Chinar Dairy',
        theme: AppTheme.lightTheme,
        debugShowCheckedModeBanner: false,
        initialRoute: '/',
        routes: {
          '/': (context) => const SplashScreen(),
          '/login': (context) => const LoginScreen(),
          '/otp': (context) => const OTPScreen(),
          '/zone-selection': (context) => const ZoneSelectionScreen(),
          '/main': (context) => const MainScreen(),
          '/product-detail': (context) => const ProductDetailScreen(),
          '/subscription': (context) => const SubscriptionScreen(),
          '/address-selection': (context) => const AddressSelectionScreen(),
          '/address-management': (context) => const AddressManagementScreen(),
          '/cart': (context) => const CartScreen(),
          '/payment': (context) => const PaymentScreen(totalAmount: 0, paymentType: ''), // Add default for routes map
          '/profile': (context) => const ProfileScreen(),
          '/referral': (context) => const ReferralScreen(),
          '/wallet': (context) => const WalletScreen(),
          '/invoices': (context) => const InvoicesScreen(), 
        },
        onGenerateRoute: (settings) {
          if (settings.name == '/payment') {
            final args = settings.arguments as Map<String, dynamic>;
            return MaterialPageRoute(
              builder: (context) => PaymentScreen(
                totalAmount: args['totalAmount'],
                paymentType: args['paymentType'],
                orderData: args['orderData'],
              ),
            );
          }
          return null;
        },
      ),
    );
  }
}